### ISSUE TITLE
Failed at step EXEC spawning /var/lib/activemq-brokers/%i/bin/artemis-service: No such file or directory

### ISSUE THREAD

**Issue by leandropissurno** [markt-de/puppet-activemq#3] opened 2022-02-23 12:40 UTC
Hello. I'm having a issue when try to provision artemis in single instance. Thats my hieradata:

```yaml
activemq::version: "2.19.0"
activemq::download_url: "http://archive.apache.org/dist/activemq/activemq-artemis/2.19.0/apache-artemis-2.19.0-bin.tar.gz"
activemq::checksum: "dec3227cac1eb864c1c7f229cb9b392d3fa38f5022579375fda1ba378997b166cf13e4f0182a1081c6e8592e737ac665e3b4c7fb7795646ba2122d2c9a18d550"
activemq::cluster_name: "cluster-artemis"
activemq::admin_user: "admin"
activemq::admin_password: "vagrant"
activemq::instances:
  instance1:
    bind: "%{facts.networking.interfaces.eth0.ip}"
    port: 61616
    web_bind: "%{facts.networking.interfaces.eth0.ip}"
    web_port: 8161
    acceptors:
      artemis:
        port: 61616
      amqp: 
        port: 5672
```

I receive this output below

```log
Debug: Executing: '/usr/bin/systemctl is-active activemq@instance1'
Debug: Executing: '/usr/bin/systemctl is-enabled activemq@instance1'
Debug: Executing: '/usr/bin/systemctl unmask activemq@instance1'
Debug: Executing: '/usr/bin/systemctl start activemq@instance1'
Debug: Running journalctl command to get logs for systemd start failure: journalctl -n 50 --since '5 minutes ago' -u activemq@instance1 --no-pager
Debug: Executing: 'journalctl -n 50 --since '5 minutes ago' -u activemq@instance1 --no-pager'
Error: Systemd start for activemq@instance1 failed!
journalctl log for activemq@instance1:
-- Logs begin at Tue 2022-02-22 16:56:00 -03, end at Wed 2022-02-23 09:25:31 -03. --
Feb 23 09:20:41 n221t032294 systemd[1]: activemq@instance1.service holdoff time over, scheduling restart.
Feb 23 09:20:41 n221t032294 systemd[1]: Starting "ActiveMQ Artemis instance instance1"...
Feb 23 09:20:41 n221t032294 systemd[1]: activemq@instance1.service: control process exited, code=exited status=203
Feb 23 09:20:41 n221t032294 systemd[1]: Failed to start "ActiveMQ Artemis instance instance1".
Feb 23 09:20:41 n221t032294 systemd[1]: Unit activemq@instance1.service entered failed state.
Feb 23 09:20:41 n221t032294 systemd[1]: activemq@instance1.service failed.
Feb 23 09:20:51 n221t032294 systemd[1]: activemq@instance1.service holdoff time over, scheduling restart.
Feb 23 09:20:51 n221t032294 systemd[1]: Starting "ActiveMQ Artemis instance instance1"...
Feb 23 09:20:51 n221t032294 systemd[1]: activemq@instance1.service: control process exited, code=exited status=203
Feb 23 09:20:51 n221t032294 systemd[1]: Failed to start "ActiveMQ Artemis instance instance1".
Feb 23 09:20:51 n221t032294 systemd[1]: Unit activemq@instance1.service entered failed state.
Feb 23 09:20:51 n221t032294 systemd[1]: activemq@instance1.service failed.
Feb 23 09:21:01 n221t032294 systemd[1]: activemq@instance1.service holdoff time over, scheduling restart.
Feb 23 09:21:01 n221t032294 systemd[1]: Starting "ActiveMQ Artemis instance instance1"...
Feb 23 09:21:01 n221t032294 systemd[1]: activemq@instance1.service: control process exited, code=exited status=203
Feb 23 09:21:01 n221t032294 systemd[1]: Failed to start "ActiveMQ Artemis instance instance1".
Feb 23 09:21:01 n221t032294 systemd[1]: Unit activemq@instance1.service entered failed state.
Feb 23 09:21:01 n221t032294 systemd[1]: activemq@instance1.service failed.
Feb 23 09:21:11 n221t032294 systemd[1]: activemq@instance1.service holdoff time over, scheduling restart.
Feb 23 09:21:11 n221t032294 systemd[1]: Starting "ActiveMQ Artemis instance instance1"...
Feb 23 09:21:11 n221t032294 systemd[1]: activemq@instance1.service: control process exited, code=exited status=203
Feb 23 09:21:11 n221t032294 systemd[1]: Failed to start "ActiveMQ Artemis instance instance1".
Feb 23 09:21:11 n221t032294 systemd[1]: Unit activemq@instance1.service entered failed state.
Feb 23 09:21:11 n221t032294 systemd[1]: activemq@instance1.service failed.
Feb 23 09:21:22 n221t032294 systemd[1]: activemq@instance1.service holdoff time over, scheduling restart.
Feb 23 09:21:22 n221t032294 systemd[1]: Starting "ActiveMQ Artemis instance instance1"...
Feb 23 09:21:22 n221t032294 systemd[16140]: Failed at step EXEC spawning /var/lib/activemq-brokers/%i/bin/artemis-service: No such file or directory
```

**Comment by fraenki** [comment] 2022-10-18 13:28
Closing because I cannot reproduce this issue. Issue may be re-opened if someone could provide the required information.

**Closed by fraenki** 2022-10-18 13:28 UTC
Labels: question

**Comment by fraenki** [comment] 2022-10-19 11:58
I've also added acceptance tests for most recent versions of Rocky, Debian and Ubuntu. They confirm that everything is working in the current version of this module. :)
